const API_KEY=process.env.API_KEY;
export default{
    fetchTrending:{
        gener:'fetchTrending',
        title:'Trending',
        url:`/trending/all/week?api_key=${API_KEY}&language-en-US`
    },
    fetchTopRated:{
        gener:'fetchTopRated',
        title:'Top Rated',
        url:`/movie/top_rated/?api_key=${API_KEY}&language-en-US`
    },
    fetchActionMovies:{
        gener:'fetchActionMovies',
        title:'Action',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=28`
    },
    fetchComedyMovies:{
        gener:'fetchComedyMovies',
        title:'Comedy',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=35`
    },
    fetchHorrorMovies:{
        gener:'fetchHorrorMovies',
        title:'Horror',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=27`
    },
    fetchRomanceMovies:{
        gener:'fetchRomanceMovies',
        title:'Romance',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=10749`
    },
    fetchMystery:{
        gener:'fetchMystery',
        title:'Mystery',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=9648`
    },
    fetchSciFi:{
        gener:'fetchSciFi',
        title:'Mystery',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=878`
    },
    fetchMystery:{
        gener:'fetchMystery',
        title:'Sci-Fi',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=37`
    },
    fetchWestern:{
        gener:'fetchWestern',
        title:'Western',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=16`
    },
    fetchTV:{
        gener:'fetchTV',
        title:'TV Movies',
        url:`/discover/movie/?api_key=${API_KEY}&with_genres=10770`
    },
}